#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Cloud-init user-data script for PI Health Dashboard
# Runs once on first boot to provision the EC2 instance
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
exec > /var/log/pi-dashboard-setup.log 2>&1

echo "=== PI Dashboard Setup Starting $(date) ==="

# ─── System updates ──────────────────────────────────────────────────────────
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  ca-certificates curl gnupg lsb-release \
  git apache2-utils unzip jq

# ─── Install Docker ──────────────────────────────────────────────────────────
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
  gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Enable and start Docker
systemctl enable docker
systemctl start docker

# Allow ubuntu user to run docker without sudo
usermod -aG docker ubuntu

# ─── Clone the repository ────────────────────────────────────────────────────
APP_DIR="/opt/pi-dashboard"
git clone --depth 1 --branch "${github_branch}" \
  "https://github.com/${github_repo}.git" "$APP_DIR"

cd "$APP_DIR"

# ─── Generate .env file ─────────────────────────────────────────────────────
cat > .env <<EOF
# Auto-generated by Terraform cloud-init
UPLOAD_API_KEY=${upload_api_key}
CORS_ORIGINS=http://localhost,https://${domain_name}
DB_URL=sqlite:///./app.db
BACKEND_URL=http://backend:8000
EOF

# ─── Generate .htpasswd (basic auth for nginx) ──────────────────────────────
htpasswd -cb .htpasswd admin "${app_password}"
chmod 600 .htpasswd

# ─── Write production nginx config ──────────────────────────────────────────
mkdir -p nginx
cat > nginx/nginx.conf <<'NGINX'
events { worker_connections 1024; }

http {
    upstream frontend { server frontend:3000; }
    upstream backend  { server backend:8000;  }

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;
    limit_req_zone $binary_remote_addr zone=upload:10m rate=2r/s;

    server {
        listen 80;
        server_name _;

        # Let's Encrypt challenge (if domain is configured)
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect to HTTPS if certs exist
        location / {
            # Basic auth
            auth_basic "PI Dashboard";
            auth_basic_user_file /etc/nginx/.htpasswd;

            # Proxy to frontend
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API - no basic auth (has its own upload key)
        location /api/ {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 10m;
        }

        # Upload endpoint - stricter rate limit
        location /api/upload {
            limit_req zone=upload burst=3 nodelay;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10m;
        }

        # Health check (no auth)
        location /health {
            proxy_pass http://backend/health;
        }
    }
}
NGINX

# ─── Write production docker-compose override ────────────────────────────────
cat > docker-compose.prod.yml <<'COMPOSE'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pi-backend
    restart: unless-stopped
    volumes:
      - db-data:/app
    env_file: .env
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=
    container_name: pi-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000
    expose:
      - "3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: pi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db-data:
  certbot-etc:
  certbot-www:
COMPOSE

# ─── Build and start ─────────────────────────────────────────────────────────
docker compose -f docker-compose.prod.yml build
docker compose -f docker-compose.prod.yml up -d

# ─── Create deploy script for CI/CD ─────────────────────────────────────────
cat > /opt/pi-dashboard/deploy-prod.sh <<'DEPLOY'
#!/bin/bash
set -e
cd /opt/pi-dashboard
echo "=== Deploying PI Dashboard $(date) ==="
git pull
docker compose -f docker-compose.prod.yml build
docker compose -f docker-compose.prod.yml up -d --remove-orphans
echo "=== Deploy complete ==="
DEPLOY
chmod +x /opt/pi-dashboard/deploy-prod.sh

# ─── Setup Let's Encrypt (if domain is configured) ───────────────────────────
%{ if domain_name != "" }
echo "=== Setting up Let's Encrypt for ${domain_name} ==="
apt-get install -y certbot

# Wait for DNS to propagate and nginx to be ready
sleep 10

certbot certonly --webroot \
  -w /var/lib/docker/volumes/pi-dashboard_certbot-www/_data \
  -d "${domain_name}" \
  --email "${admin_email}" \
  --agree-tos \
  --non-interactive || echo "Certbot failed — you can run it manually later"

# Add HTTPS server block to nginx config
cat >> nginx/nginx.conf <<'HTTPS_BLOCK'

    server {
        listen 443 ssl;
        server_name ${domain_name};

        ssl_certificate /etc/letsencrypt/live/${domain_name}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${domain_name}/privkey.pem;

        location / {
            auth_basic "PI Dashboard";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10m;
        }

        location /health {
            proxy_pass http://backend/health;
        }
    }
HTTPS_BLOCK

docker compose -f docker-compose.prod.yml restart nginx

# Auto-renew cron
echo "0 3 * * * certbot renew --quiet && docker compose -f /opt/pi-dashboard/docker-compose.prod.yml restart nginx" | \
  crontab -
%{ endif }

# ─── Setup automatic security updates ────────────────────────────────────────
apt-get install -y unattended-upgrades
echo 'Unattended-Upgrade::Automatic-Reboot "false";' > \
  /etc/apt/apt.conf.d/52-no-reboot

echo "=== PI Dashboard Setup Complete $(date) ==="
echo "Access at: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
