const lines = [
'"use client";',
'',
'import HealthBadge from "@/components/HealthBadge";',
'import ProgressBar from "@/components/ProgressBar";',
'',
'function healthToStatus(health) {',
'  if (health === "green") return "healthy";',
'  if (health === "red") return "critical";',
'  if (health === "yellow") return "warning";',
'  return "unknown";',
'}',
'',
'function SectionLabel({ children }) {',
'  return (',
'    <p style={{ fontFamily: "var(--font-mono)", fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: 4 }}>',
'      {children}',
'    </p>',
'  );',
'}',
'',
'export default function PICard({ pi }) {',
'  const status = healthToStatus(pi.health);',
'  const href = "/pi/" + pi.name;',
'',
'  return (',
'    <a',
'      href={href}',
'      style={{ display: "block", background: "var(--bg-card)", border: "1px solid var(--border)", borderRadius: 4, padding: "20px 24px", textDecoration: "none", transition: "border-color 0.15s, background 0.15s, transform 0.15s", cursor: "pointer" }}',
'      onMouseEnter={(e) => {',
'        e.currentTarget.style.borderColor = "var(--border-strong)";',
'        e.currentTarget.style.background = "var(--bg-hover)";',
'        e.currentTarget.style.transform = "translateY(-1px)";',
'      }}',
'      onMouseLeave={(e) => {',
'        e.currentTarget.style.borderColor = "var(--border)";',
'        e.currentTarget.style.background = "var(--bg-card)";',
'        e.currentTarget.style.transform = "translateY(0)";',
'      }}',
'    >',
'      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>',
'        <div>',
'          <p style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--text-muted)", letterSpacing: "0.1em", marginBottom: 4 }}>PI</p>',
'          <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 700, color: "var(--text-primary)" }}>',
'            {pi.name}',
'          </h2>',
'        </div>',
'        <HealthBadge status={status} />',
'      </div>',
'      <div style={{ marginBottom: 16 }}>',
'        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>',
'          <SectionLabel>Completion</SectionLabel>',
'          <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--text-secondary)" }}>',
'            {pi.done_issues} / {pi.total_issues} issues',
'          </span>',
'        </div>',
'        <ProgressBar value={pi.pct_complete || 0} status={status} />',
'      </div>',
'      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, paddingTop: 16, borderTop: "1px solid var(--border)" }}>',
'        {[',
'          { label: "Sprints", value: pi.sprints.length },',
'          { label: "Issues", value: pi.total_issues },',
'          { label: "Blocked", value: pi.blocked_issues },',
'        ].map(({ label, value }) => (',
'          <div key={label}>',
'            <SectionLabel>{label}</SectionLabel>',
'            <p style={{ fontFamily: "var(--font-mono)", fontSize: 16, fontWeight: 600, color: label === "Blocked" && value > 0 ? "var(--status-critical)" : "var(--text-primary)" }}>',
'              {value}',
'            </p>',
'          </div>',
'        ))}',
'      </div>',
'      {pi.sprints.length > 0 && (',
'        <div style={{ marginTop: 16 }}>',
'          <SectionLabel>Sprints</SectionLabel>',
'          <div style={{ display: "flex", gap: 3, marginTop: 6, alignItems: "flex-end", height: 28 }}>',
'            {pi.sprints.map((s) => {',
'              const pct = s.pct_complete || 0;',
'              const color = s.state === "closed" ? "var(--status-healthy)" : s.state === "active" ? "var(--status-warning)" : "var(--text-muted)";',
'              return (',
'                <div key={s.jira_id} title={s.name + ": " + pct + "%"} style={{ flex: 1, background: "var(--track-bg)", borderRadius: 2, height: "100%", position: "relative", overflow: "hidden" }}>',
'                  <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: pct + "%", background: color, opacity: 0.8, borderRadius: 2 }} />',
'                </div>',
'              );',
'            })}',
'          </div>',
'        </div>',
'      )}',
'    </a>',
'  );',
'}',
];
require('fs').writeFileSync('components/PICard.tsx', lines.join('\n'));
console.log('PICard.tsx done');