const fs = require('fs');

const lines = [
  '"use client";',
  '',
  'import type { PIHealth } from "@/lib/api";',
  'import HealthBadge from "@/components/HealthBadge";',
  'import ProgressBar from "@/components/ProgressBar";',
  '',
  'function SectionLabel({ children }: { children: React.ReactNode }) {',
  '  return (',
  '    <p',
  '      style={{',
  '        fontFamily: "var(--font-mono)",',
  '        fontSize: 10,',
  '        fontWeight: 700,',
  '        letterSpacing: "0.12em",',
  '        textTransform: "uppercase" as const,',
  '        color: "var(--text-muted)",',
  '        marginBottom: 4,',
  '      }}',
  '    >',
  '      {children}',
  '    </p>',
  '  );',
  '}',
  '',
  'export default function PICard({ pi }: { pi: PIHealth }) {',
  '  const done = pi.completed_points;',
  '  const total = pi.total_points;',
  '  const href = "/pi/" + pi.pi_id;',
  '',
  '  return (',
  '    <a',
  '      href={href}',
  '      style={{',
  '        display: "block",',
  '        background: "var(--bg-card)",',
  '        border: "1px solid var(--border)",',
  '        borderRadius: 4,',
  '        padding: "20px 24px",',
  '        textDecoration: "none",',
  '        transition: "border-color 0.15s, background 0.15s, transform 0.15s",',
  '        cursor: "pointer",',
  '      }}',
  '      onMouseEnter={(e) => {',
  '        const el = e.currentTarget as HTMLAnchorElement;',
  '        el.style.borderColor = "var(--border-strong)";',
  '        el.style.background = "var(--bg-hover)";',
  '        el.style.transform = "translateY(-1px)";',
  '      }}',
  '      onMouseLeave={(e) => {',
  '        const el = e.currentTarget as HTMLAnchorElement;',
  '        el.style.borderColor = "var(--border)";',
  '        el.style.background = "var(--bg-card)";',
  '        el.style.transform = "translateY(0)";',
  '      }}',
  '    >',
  '      <div',
  '        style={{',
  '          display: "flex",',
  '          justifyContent: "space-between",',
  '          alignItems: "flex-start",',
  '          marginBottom: 16,',
  '        }}',
  '      >',
  '        <div>',
  '          <p',
  '            style={{',
  '              fontFamily: "var(--font-mono)",',
  '              fontSize: 10,',
  '              color: "var(--text-muted)",',
  '              letterSpacing: "0.1em",',
  '              marginBottom: 4,',
  '            }}',
  '          >',
  '            {pi.pi_id}',
  '          </p>',
  '          <h2',
  '            style={{',
  '              fontFamily: "var(--font-display)",',
  '              fontSize: 20,',
  '              fontWeight: 700,',
  '              letterSpacing: "0.02em",',
  '              color: "var(--text-primary)",',
  '            }}',
  '          >',
  '            {pi.pi_name}',
  '          </h2>',
  '        </div>',
  '        <HealthBadge status={pi.status} />',
  '      </div>',
  '      <div style={{ marginBottom: 16 }}>',
  '        <div',
  '          style={{',
  '            display: "flex",',
  '            justifyContent: "space-between",',
  '            marginBottom: 6,',
  '          }}',
  '        >',
  '          <SectionLabel>Completion</SectionLabel>',
  '          <span',
  '            style={{',
  '              fontFamily: "var(--font-mono)",',
  '              fontSize: 10,',
  '              color: "var(--text-secondary)",',
  '            }}',
  '          >',
  '            {done} / {total} pts',
  '          </span>',
  '        </div>',
  '        <ProgressBar value={pi.completion_rate * 100} status={pi.status} />',
  '      </div>',
  '      <div',
  '        style={{',
  '          display: "grid",',
  '          gridTemplateColumns: "repeat(3, 1fr)",',
  '          gap: 12,',
  '          paddingTop: 16,',
  '          borderTop: "1px solid var(--border)",',
  '        }}',
  '      >',
  '        {[',
  '          { label: "Sprints", value: pi.sprints.length },',
  '          { label: "Issues", value: pi.issue_count },',
  '          { label: "Health", value: Math.round(pi.health_score) },',
  '        ].map(({ label, value }) => (',
  '          <div key={label}>',
  '            <SectionLabel>{label}</SectionLabel>',
  '            <p',
  '              style={{',
  '                fontFamily: "var(--font-mono)",',
  '                fontSize: 16,',
  '                fontWeight: 600,',
  '                color:',
  '                  label === "Health"',
  '                    ? value >= 75',
  '                      ? "var(--status-healthy)"',
  '                      : value >= 50',
  '                      ? "var(--status-warning)"',
  '                      : "var(--status-critical)"',
  '                    : "var(--text-primary)",',
  '              }}',
  '            >',
  '              {value}',
  '            </p>',
  '          </div>',
  '        ))}',
  '      </div>',
  '      {pi.sprints.length > 0 && (',
  '        <div style={{ marginTop: 16 }}>',
  '          <SectionLabel>Sprints</SectionLabel>',
  '          <div',
  '            style={{',
  '              display: "flex",',
  '              gap: 3,',
  '              marginTop: 6,',
  '              alignItems: "flex-end",',
  '              height: 28,',
  '            }}',
  '          >',
  '            {pi.sprints.map((s) => {',
  '              const pct = Math.round(s.completion_rate * 100);',
  '              const color =',
  '                s.status === "healthy"',
  '                  ? "var(--status-healthy)"',
  '                  : s.status === "warning"',
  '                  ? "var(--status-warning)"',
  '                  : s.status === "critical"',
  '                  ? "var(--status-critical)"',
  '                  : "var(--text-muted)";',
  '              return (',
  '                <div',
  '                  key={s.sprint_id}',
  '                  title={s.sprint_name + ": " + pct + "%"}',
  '                  style={{',
  '                    flex: 1,',
  '                    background: "var(--track-bg)",',
  '                    borderRadius: 2,',
  '                    height: "100%",',
  '                    position: "relative",',
  '                    overflow: "hidden",',
  '                  }}',
  '                >',
  '                  <div',
  '                    style={{',
  '                      position: "absolute",',
  '                      bottom: 0,',
  '                      left: 0,',
  '                      right: 0,',
  '                      height: pct + "%",',
  '                      background: color,',
  '                      opacity: 0.8,',
  '                      borderRadius: 2,',
  '                    }}',
  '                  />',
  '                </div>',
  '              );',
  '            })}',
  '          </div>',
  '        </div>',
  '      )}',
  '    </a>',
  '  );',
  '}',
];

require('fs').writeFileSync('components/PICard.tsx', lines.join('\n'));
console.log('Done');